name: jab_zindagi_shuru_hogi_inzaar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  curved_navigation_bar: ^1.0.6
  equatable: ^2.0.7
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  share_plus: ^10.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/book_cover.png
    - assets/images/light_cover.png
    - assets/images/sepia_cover.png
    - assets/images/sepia.png
    - assets/images/stars_bg.jpg
    - assets/images/author.png
    - assets/images/splash.png

  fonts:
    - family: Urdu
      fonts:
        - asset: assets/fonts/jameel_noori.ttf
